### PR TITLE
Added a parted controller for scrollIndicatorsInsets

### PR DESCRIPTION
**Pull request by K-Be**

### CODE REVIEW

**Comment by kirpichenko** [comment]
Why do you need contentInsets applying for content and scroll indicator in separate controllers?
Also example project is crashing now with exception: -[UIScrollView _systemGestureStateChanged:]: message sent to deallocated instance
It's easy to reproduce. Run example, click Show next button, go back and try to present keyboard.

**Comment by K-Be** [comment]
In my project I need separated insets for contentInsets and scrollIndicatorsInsets. I’ve tried add this code in EKKeyboardAvoidingProvider and saw what it is not clear. It’s generated many doubling lines of code. May be exist more better solution to implement the separated insets.

I can’t reproduce the crash. May be exist special conditions. I’ve tried on iPhone Simulator (different versions), iOS 7 (a device), iOS 6 (a device).

**Comment by K-Be** [comment]
Can you give me link  to merged branch? I will see, may be it error's arrived after merge.

**Comment by kirpichenko** [comment]
I haven't merged it yet.I just cloned your master branch and saw the crash. I think I need some more time to test it.

**Pull request closed without merging**
